export class RoundNotGame {
  constructor(canvas,onStats,onPhase,onFinish){this.c=canvas;this.x=canvas.getContext('2d');this.onStats=onStats;this.onPhase=onPhase;this.onFinish=onFinish;this.players=[];this.phase='green';this.running=false;this.duration=180;this.time=180;this.last=0;this.phaseLeft=3;this.finishers=[];this.resize();addEventListener('resize',()=>this.resize())}
  resize(){const r=this.c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);this.w=r.width;this.h=r.height;this.c.width=r.width*d;this.c.height=r.height*d;this.x.setTransform(d,0,0,d,0,0)}
  addPlayer(user){if(this.players.some(p=>p.user===user))return;const lane=(this.players.length%10+.5)/10;this.players.push({user,x:this.w*(.1+lane*.8),y:this.h*.88,alive:true,done:false,speed:18+Math.random()*28,reaction:.06+Math.random()*.32,freeze:0,color:`hsl(${100+Math.random()*55} 65% ${45+Math.random()*15}%)`});this.stats()}
  seed(n=32){for(let i=1;i<=n;i++)this.addPlayer(`@user${String(i).padStart(2,'0')}`)}
  start(){this.running=true;this.time=this.duration;this.phase='green';this.phaseLeft=this.nextPhase();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
  nextPhase(){return this.phase==='green'?2.4+Math.random()*4.2:1.4+Math.random()*2.6}
  switchPhase(){this.phase=this.phase==='green'?'red':'green';this.phaseLeft=this.nextPhase();if(this.phase==='red')for(const p of this.players)if(p.alive&&!p.done)p.freeze=Math.random()<p.reaction?.55+Math.random()*.3:0;this.onPhase(this.phase)}
  update(dt){if(!this.running)return;this.time-=dt;this.phaseLeft-=dt;if(this.phaseLeft<=0)this.switchPhase();for(const p of this.players){if(!p.alive||p.done)continue;if(this.phase==='green'){p.y-=p.speed*dt*(.75+Math.random()*.5)}else if(p.freeze>0){p.y-=p.speed*dt*.72;p.freeze-=dt;if(p.freeze<=0&&Math.random()<.82)p.alive=false}if(p.y<this.h*.15){p.done=true;this.finishers.push(p)}}if(this.time<=0||this.players.every(p=>!p.alive||p.done)){this.running=false;for(const p of this.players)if(!p.done)p.alive=false;this.stats();this.onFinish(this.finishers)}this.stats()}
  stats(){this.onStats({alive:this.players.filter(p=>p.alive&&!p.done).length,finished:this.finishers.length,dead:this.players.filter(p=>!p.alive).length,time:Math.max(0,this.time)})}
  draw(){const g=this.x,w=this.w,h=this.h;g.clearRect(0,0,w,h);const sky=g.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#183f29');sky.addColorStop(1,'#07120c');g.fillStyle=sky;g.fillRect(0,0,w,h);g.fillStyle='#10281a';g.fillRect(0,h*.13,w,h*.87);for(let i=0;i<11;i++){g.strokeStyle='#23452f';g.beginPath();g.moveTo(w*i/10,h*.13);g.lineTo(w*(i/10-.18)+w*.18,h);g.stroke()}g.fillStyle='#55ff88';g.fillRect(0,h*.14,w,3);g.font='800 11px system-ui';g.fillText('CHEGADA',12,h*.14-8);this.drawWatcher(g,w/2,h*.08);for(const p of this.players)this.drawPlayer(g,p)}
  drawWatcher(g,x,y){g.save();g.translate(x,y);const watch=this.phase==='red';g.fillStyle=watch?'#ff4b57':'#68ff91';g.shadowColor=g.fillStyle;g.shadowBlur=18;g.beginPath();g.arc(0,0,24,0,Math.PI*2);g.fill();g.shadowBlur=0;g.fillStyle='#06100a';g.fillRect(-13,21,26,25);if(watch){g.fillStyle='#111';g.beginPath();g.arc(-8,-3,3,0,7);g.arc(8,-3,3,0,7);g.fill()}g.restore()}
  drawPlayer(g,p){g.save();g.globalAlpha=p.alive?1:.25;g.translate(p.x,p.y);g.fillStyle=p.alive?p.color:'#5b6660';g.beginPath();g.arc(0,-13,7,0,7);g.fill();g.fillRect(-6,-6,12,19);g.strokeStyle=g.fillStyle;g.lineWidth=4;g.beginPath();g.moveTo(-3,12);g.lineTo(-7,23);g.moveTo(3,12);g.lineTo(7,23);g.stroke();g.font='700 10px system-ui';g.textAlign='center';g.fillStyle=p.alive?'#f1fff6':'#ff7777';g.fillText(p.alive?p.user:`F ${p.user}`,0,-27);g.restore()}
  loop(t){const dt=Math.min((t-this.last)/1000,.05);this.last=t;this.update(dt);this.draw();if(this.running)requestAnimationFrame(v=>this.loop(v))}
}