export class RoundNotGame {
constructor(canvas,onStats,onPhase,onFinish){this.c=canvas;this.x=canvas.getContext('2d');this.onStats=onStats;this.onPhase=onPhase;this.onFinish=onFinish;this.players=[];this.phase='green';this.running=false;this.duration=180;this.time=180;this.last=0;this.phaseLeft=3;this.finishers=[];this.resize();addEventListener('resize',()=>this.resize())}
resize(){const oldW=this.w||0,oldH=this.h||0,r=this.c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);this.w=r.width;this.h=r.height;if(oldW>0&&oldH>0&&this.players.length){const sx=this.w/oldW,sy=this.h/oldH;for(const p of this.players){p.x*=sx;p.y*=sy;p.speed*=sy}}this.c.width=Math.max(1,Math.round(r.width*d));this.c.height=Math.max(1,Math.round(r.height*d));this.x.setTransform(d,0,0,d,0,0);if(this.players.length)this.draw()}
addPlayer(user){if(this.players.some(p=>p.user===user))return;const id=this.players.length+1,cols=9,row=Math.floor((id-1)/cols),col=(id-1)%cols;this.players.push({id,user,x:this.w*(.08+.84*((col+.5)/cols))+(row%2?7:0),y:this.h*(.91-row*.055),alive:true,done:false,speed:this.h*(.03+Math.random()*.045),reaction:.06+Math.random()*.32,freeze:0,step:Math.random()*6.2});this.stats()}
seed(n=32){for(let i=1;i<=n;i++)this.addPlayer(`@user${String(i).padStart(2,'0')}`)}
start(){this.running=true;this.time=this.duration;this.phase='green';this.phaseLeft=this.nextPhase();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
nextPhase(){return this.phase==='green'?2.6+Math.random()*4:1.5+Math.random()*2.4}
switchPhase(){this.phase=this.phase==='green'?'red':'green';this.phaseLeft=this.nextPhase();if(this.phase==='red')for(const p of this.players)if(p.alive&&!p.done)p.freeze=Math.random()<p.reaction?.55+Math.random()*.3:0;this.onPhase(this.phase)}
update(dt){if(!this.running)return;this.time-=dt;this.phaseLeft-=dt;if(this.phaseLeft<=0)this.switchPhase();for(const p of this.players){if(!p.alive||p.done)continue;if(this.phase==='green'){p.step+=dt*8;p.y-=p.speed*dt*(.75+Math.random()*.5)}else if(p.freeze>0){p.y-=p.speed*dt*.72;p.freeze-=dt;if(p.freeze<=0&&Math.random()<.82)p.alive=false}if(p.y<this.h*.25){p.done=true;this.finishers.push(p)}}if(this.time<=0||this.players.every(p=>!p.alive||p.done)){this.running=false;for(const p of this.players)if(!p.done)p.alive=false;this.stats();this.onFinish(this.finishers)}this.stats()}
stats(){this.onStats({alive:this.players.filter(p=>p.alive&&!p.done).length,finished:this.finishers.length,dead:this.players.filter(p=>!p.alive).length,time:Math.max(0,this.time)})}
draw(){const g=this.x,w=this.w,h=this.h;g.clearRect(0,0,w,h);const bg=g.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#153d28');bg.addColorStop(.25,'#33543b');bg.addColorStop(1,'#77715b');g.fillStyle=bg;g.fillRect(0,0,w,h);g.fillStyle='#11281b';g.fillRect(0,0,w,h*.18);for(let i=0;i<14;i++){const y=h*(.25+i*.055);g.strokeStyle='rgba(40,35,25,.14)';g.beginPath();g.moveTo(w*.03,y);g.lineTo(w*.97,y);g.stroke()}const fy=h*.22;g.fillStyle='#ff3949';g.shadowColor='#ff3949';g.shadowBlur=9;g.fillRect(w*.06,fy,w*.88,3);g.shadowBlur=0;g.fillStyle='#eaffef';g.font='900 11px system-ui';g.fillText('CHEGADA',12,fy-8);this.drawWatcher(g,w/2,h*.13);[...this.players].sort((a,b)=>a.y-b.y).forEach(p=>this.drawPlayer(g,p))}
drawWatcher(g,x,y){g.save();g.translate(x,y);const watch=this.phase==='red';g.fillStyle=watch?'#ff4c55':'#79ff98';g.shadowColor=g.fillStyle;g.shadowBlur=18;g.beginPath();g.arc(0,0,27,0,Math.PI*2);g.fill();g.shadowBlur=0;g.fillStyle='#07100b';g.fillRect(-22,25,44,43);if(watch){g.fillStyle='#111';g.beginPath();g.arc(-9,-3,3.5,0,7);g.arc(9,-3,3.5,0,7);g.fill()}g.fillStyle='#ff3d4b';g.fillRect(-18,35,36,23);g.fillStyle='#170607';g.font='900 17px ui-monospace,monospace';g.textAlign='center';g.textBaseline='middle';g.fillText(String(Math.max(0,Math.ceil(this.phaseLeft))).padStart(2,'0'),0,47);g.restore()}
drawPlayer(g,p){const s=.72+.38*(p.y/this.h),moving=this.phase==='green'&&p.alive&&!p.done;g.save();g.globalAlpha=p.alive?1:.3;g.translate(p.x,p.y);g.scale(s,s);const bob=moving?Math.sin(p.step)*1.7:0;g.translate(0,bob);g.fillStyle=p.alive?'#078c81':'#59615c';g.fillRect(-7,-7,14,18);g.strokeStyle=g.fillStyle;g.lineWidth=4;g.lineCap='round';g.beginPath();g.moveTo(-3,10);g.lineTo(-7,22+(moving?Math.sin(p.step)*3:0));g.moveTo(3,10);g.lineTo(7,22-(moving?Math.sin(p.step)*3:0));g.stroke();g.fillStyle='#242925';g.beginPath();g.arc(0,-16,8,0,7);g.fill();g.textAlign='center';g.lineJoin='round';g.font='800 10px system-ui';g.lineWidth=3;g.strokeStyle='#07100b';g.strokeText(p.user,0,-31);g.fillStyle='#fff';g.fillText(p.user,0,-31);g.font='900 10px system-ui';g.lineWidth=3;g.strokeText(String(p.id),0,5);g.fillStyle='#fff';g.fillText(String(p.id),0,5);g.restore()}
loop(t){const dt=Math.min((t-this.last)/1000,.05);this.last=t;this.update(dt);this.draw();if(this.running)requestAnimationFrame(v=>this.loop(v))}
}